# Generated by Django 3.1.5 on 2021-05-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siguplogin', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
