# Generated by Django 3.1.5 on 2021-01-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_estore'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.estore'),
        ),
    ]
