# Generated by Django 3.1.5 on 2021-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
