# Generated by Django 3.1.5 on 2021-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0002_auto_20210503_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='customer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='link',
            name='nemail',
            field=models.BooleanField(default=False),
        ),
    ]
