# Generated by Django 3.1.5 on 2021-05-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0003_auto_20210507_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='max_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='min_target',
            field=models.FloatField(default=0),
        ),
    ]
