# Generated by Django 3.1.5 on 2021-05-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('subheading1', models.CharField(max_length=500)),
                ('subheading2', models.CharField(blank=True, max_length=500)),
                ('subheading3', models.CharField(blank=True, max_length=500)),
                ('para1', models.CharField(max_length=1000)),
                ('para2', models.CharField(blank=True, max_length=1000)),
                ('para3', models.CharField(blank=True, max_length=1000)),
                ('img_1', models.ImageField(upload_to='uploads/blog/')),
                ('img_2', models.ImageField(blank=True, upload_to='uploads/blog/')),
            ],
        ),
    ]
