# Generated by Django 3.1.5 on 2021-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techblog',
            name='para1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='para2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='para3',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
