# Generated by Django 3.1.5 on 2021-05-08 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0002_auto_20210508_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='techblog',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
