# Generated by Django 3.1.5 on 2021-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0003_techblog_uploaded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='techblog',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='uploads/blog/'),
        ),
        migrations.AddField(
            model_name='techblog',
            name='link',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
