# Generated by Django 3.1.5 on 2021-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0004_auto_20210508_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techblog',
            name='link',
        ),
        migrations.AddField(
            model_name='techblog',
            name='video',
            field=models.URLField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='heading',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='para1',
            field=models.TextField(max_length=50),
        ),
    ]
